### ISSUE TITLE
Minor bug in UI_for_files_selection_(1.0)

### ISSUE THREAD

**Issue by MarieVM** [Luc-mic/Projet_RMN_EMMA#6]
**Describe the bug**

/usr/bin/python3.8 /home/marievelamena/Projet/L2/Projet_RMN_EMMA/main.py
Traceback (most recent call last):
  File "/home/marievelamena/Projet/L2/Projet_RMN_EMMA/main.py", line 77, in <module>
    main_start()
  File "/home/marievelamena/Projet/L2/Projet_RMN_EMMA/main.py", line 51, in main_start
    module, argument = shaped_pulse.make_number_complex(data_handling.data_extractor(filename))
  File "/home/marievelamena/Projet/L2/Projet_RMN_EMMA/data_handling.py", line 16, in data_extractor
    for line in f:
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 10: invalid continuation byte

**To Reproduce**
1. Go to main.py in UI_for_files_selection_(1.0) in Pycharm
2. Add in testfiles bug_maker.txt
3. Click on run

Process finished with exit code 1

**Expected behavior**
I was expecting an error. The file is a pdf with an extension .txt.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2
 - Browser: Mozilla Firefox 
 - Version: 84

**Additional context**
The problematic file :
[bug_maker.txt](https://github.com/Luc-mic/Projet_RMN_EMMA/files/5910961/bug_maker.txt)

I don't think that's a big problem if it doesn't fix. It's just a limit case.

**Comment by BebertDeChast** [comment]
ce n'est pas le genre de cas que l on, doit encadrer 
par contre ce serai  intéressant de voir le résultat

**Comment by Dahan13** [comment]
Probably won't fix, maybe in a later version.
